"""add viewrship, writers & directores, and remove title for seasons

Revision ID: 05f45a4e2f9d
Revises: ed45a00b9752
Create Date: 2023-05-30 00:47:55.751834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05f45a4e2f9d'
down_revision = 'ed45a00b9752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('writtenBy', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('directedBy', sa.JSON(), nullable=False))

    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numberOfEpisodes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('viewership', sa.Float(precision=2), nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=64), nullable=False))
        batch_op.drop_column('viewership')
        batch_op.drop_column('numberOfEpisodes')

    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_column('directedBy')
        batch_op.drop_column('writtenBy')

    # ### end Alembic commands ###
