"""empty message

Revision ID: 0fd2b66298a9
Revises: 
Create Date: 2023-05-01 03:05:12.923086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd2b66298a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=64), nullable=False),
    sa.Column('middleName', sa.String(length=64), nullable=True),
    sa.Column('lastName', sa.String(length=64), nullable=False),
    sa.Column('fullName', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('club', sa.String(length=64), nullable=False),
    sa.Column('occupation', sa.String(length=64), nullable=False),
    sa.Column('recordId', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'recordId')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=64), nullable=False),
    sa.Column('episodeNumber', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=False),
    sa.Column('airDate', sa.DateTime(), nullable=False),
    sa.Column('recordId', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'recordId')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seasonOrder', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('premierDate', sa.DateTime(), nullable=False),
    sa.Column('endDate', sa.DateTime(), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=False),
    sa.Column('recordId', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'recordId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seasons')
    op.drop_table('episodes')
    op.drop_table('characters')
    # ### end Alembic commands ###
