"""episodes only as relationship + autoincrement for id

Revision ID: 1273c337bb94
Revises: 64316c465e2e
Create Date: 2023-05-06 00:53:02.914748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1273c337bb94'
down_revision = '64316c465e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seasonNumber', sa.String(length=64), nullable=False))
        batch_op.drop_constraint('episodes_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'seasons', ['seasonNumber'], ['seasonOrder'])
        batch_op.drop_column('season')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season', mysql.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('episodes_ibfk_1', 'seasons', ['season'], ['seasonOrder'])
        batch_op.drop_column('seasonNumber')

    # ### end Alembic commands ###
