"""remove age attribute

Revision ID: 48790c94b41f
Revises: 1355cc08a443
Create Date: 2023-06-02 11:33:13.517384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48790c94b41f'
down_revision = '1355cc08a443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
