"""empty message

Revision ID: 64316c465e2e
Revises: 0fd2b66298a9
Create Date: 2023-05-02 00:35:39.001210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64316c465e2e'
down_revision = '0fd2b66298a9'
branch_labels = None
depends_on = None


def upgrade():
    # create the missing index on the seasonOrder column ix_seasons_seasonOrder
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index('ix_seasons_seasonOrder', ['seasonOrder'])

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'seasons', ['season'], ['seasonOrder'])

    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['seasonOrder'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
