"""Character.age can be null

Revision ID: ed45a00b9752
Revises: 5ec2e70778e1
Create Date: 2023-05-23 00:08:32.468687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed45a00b9752'
down_revision = '5ec2e70778e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
