"""use Numeric instead of Float for viewership column

Revision ID: f83b4aedb2f3
Revises: 48790c94b41f
Create Date: 2023-06-09 11:05:05.006436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f83b4aedb2f3'
down_revision = '48790c94b41f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.alter_column('viewership',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.alter_column('viewership',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
