"""empty message

Revision ID: 3c2e0d6dab3c
Revises: 83f5e3c3416d
Create Date: 2023-04-26 23:52:47.390050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2e0d6dab3c'
down_revision = '83f5e3c3416d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=64), nullable=False),
    sa.Column('episodeNumber', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=False),
    sa.Column('airDate', sa.DateTime(), nullable=False),
    sa.Column('recordId', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'recordId')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seasonOrder', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('premierDate', sa.DateTime(), nullable=False),
    sa.Column('endDate', sa.DateTime(), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=False),
    sa.Column('recordId', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'recordId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seasons')
    op.drop_table('episodes')
    # ### end Alembic commands ###
