"""empty message

Revision ID: 86ae419a13ca
Revises: 
Create Date: 2023-04-26 23:01:47.748443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ae419a13ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('firstName', sa.String(length=64), nullable=False),
    sa.Column('middleName', sa.String(length=64), nullable=True),
    sa.Column('lastName', sa.String(length=64), nullable=False),
    sa.Column('fullName', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('club', sa.String(length=64), nullable=False),
    sa.Column('occupation', sa.String(length=64), nullable=False),
    sa.Column('recordId', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('recordId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
