"""empty message

Revision ID: f00e2279b710
Revises: 86ae419a13ca
Create Date: 2023-04-26 23:11:04.503868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f00e2279b710'
down_revision = '86ae419a13ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('firstName', sa.String(length=64), nullable=False),
    sa.Column('middleName', sa.String(length=64), nullable=True),
    sa.Column('lastName', sa.String(length=64), nullable=False),
    sa.Column('fullName', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('club', sa.String(length=64), nullable=False),
    sa.Column('occupation', sa.String(length=64), nullable=False),
    sa.Column('recordId', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('recordId')
    )
    op.drop_table('character')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('firstName', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('middleName', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('lastName', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('fullName', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('club', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('occupation', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('recordId', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('recordId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('characters')
    # ### end Alembic commands ###
